import turtle

turtle.pensize(5)
turtle.pencolor("brown")
turtle.goto(50, 0)
turtle.goto(50, 50)
turtle.goto(0,0)
turtle.goto(0, 50)
turtle.goto(50, 0)
turtle.goto(50, 50)
turtle.goto(0, 50)
turtle.pencolor("red")
turtle.goto(50, 100)
turtle.goto(50, 50)
turtle.pu()
turtle.goto(25, 80)
turtle.shape("square")
turtle.pencolor("black")
turtle.stamp()
turtle.shape("turtle")
turtle.lt(180)
turtle.goto(100, 0)
turtle.pencolor("green")
turtle.stamp()
