import turtle

turtle.speed(10)
turtle.pencolor("yellow")
turtle.goto(20, 20)
turtle.dot(80)
turtle.pu()
turtle.pencolor("red")
turtle.goto(20, 80)
turtle.dot(40)
turtle.pencolor("orange")
turtle.goto(60, 60)
turtle.dot(40)
turtle.pencolor("cyan")
turtle.goto(80, 20)
turtle.dot(40)
turtle.pencolor("pink")
turtle.goto(60, -20)
turtle.dot(40)
turtle.pencolor("purple")
turtle.goto(20, -40)
turtle.dot(40)
turtle.pencolor("blue")
turtle.goto(-20, -20)
turtle.dot(40)
turtle.pencolor("magenta")
turtle.goto(-40, 20)
turtle.dot(40)
turtle.pencolor("green")
turtle.goto(-20, 60)
turtle.dot(40)

